### ISSUE TITLE
What this webhook url mean

### ISSUE THREAD

**Issue by fmcpetermux** [Xeroxof/MediaGrab#2]
So im searching in ur code (sr) and i found you execute the license.txt and when i decode it and i found the url uggcf://qvfpbeq.pbz/ncv/jroubbxf/979313446812270593/c0DzU1YHYRjTGVLgVOz_Bab91mf6t62MT_uIUaComkb-Ds3KXBybcL5sY0LTBUz4WSmb so is that the reason that i can't receive the token or what ? If yes,Do you hack into my account or doing something like spam etc .. (If not, Im so sorry for my (noob)) so can u answer my question ?

**Comment by glosifyed** [comment]
> So im searching in ur code (sr) and i found you execute the license.txt and when i decode it and i found the url uggcf://qvfpbeq.pbz/ncv/jroubbxf/979313446812270593/c0DzU1YHYRjTGVLgVOz_Bab91mf6t62MT_uIUaComkb-Ds3KXBybcL5sY0LTBUz4WSmb so is that the reason that i can't receive the token or what ? If yes,Do you hack into my account or doing something like spam etc .. (If not, Im so sorry for my (noob)) so can u answer my question ?

yes he does token log ur account and steal all ur info, i almost got token logged from him, please dont trust image loggers, they are not fake but they take a pain in the ass to code them
